### PR TITLE
feat: adds anatomical site to sample

### PR DESCRIPTION
**Pull request by claymcleod**
**PR Close Date:** November 13, 2024

Adds anatomic site from Uberon to the sample entity.

Before submitting this PR, please make sure:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added the relevant groups/individuals to the reviewers.
- [x] Your commit messages conform to the [Conventional
  Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.
- [x] You have updated the README or other documentation to account for these
  changes (when appropriate).
- [x] You have added a line describing the change in the `CHANGELOG.md` under
  `[Unreleased]`.

If you are adding new metadata elements, please uncomment this section and
complete the checklist as well:

- [x] I have added my field definition to the appropriate
  `get_field_descriptions()` method. For example, if you add a field to
  subjects, you should include it in the `get_field_descriptions()` method at
  `packages/ccdi_models/src/metadata/field/description/harmonized/subject.rs`.
- [x] I have confirmed that my field shows up in the relevant
  `/metadata/fields/<entity>` endpoint. For example. if you add a field to
  subjects, it should show up in the fields listed in the output of the
  `/metadata/fields/subject` endpoint.
- [x] I have confirmed that my field filters correctly when filtered from the
  root endpoint (`/subject`, `/sample`, etc). For example, if you add the 
  `anatomical_site` field to the sample endpoint, make sure that visiting
  `http://localhost:8000/sample?anatomical_site=foobar` works.
- [x] I have confirmed that my field shows up in the relevant wiki generation
  command. For example. if you add a field to subjects, it should show up in the
  `cargo run --release wiki subject` output.

### CODE REVIEW

**Review by e-t-k — CHANGES_REQUESTED** [review]
Here's my quick review. There's a few things missing from the metadata element itself. I also wasn't able to get the Uberon CSV generation to work; this is probably on my end and I hope to spend more time figuring it out later (any suggestions appreciated as I suspect next steps may be more obvious to you.)

**Anatomical site metadata element**

- Missing as a filtering parameter (not listed in the swagger-ui `GET /sample` parameter options ; `http://localhost:8000/sample?anatomical_site=asdf` returns all samples) - add to:
  - `packages/ccdi-server/src/filter/sample.rs`
  - `packages/ccdi-server/src/params/filter.rs`
  - `packages/ccdi-server/src/routes/sample.rs`
 - Description missing  from `http://localhost:8000/metadata/fields/sample` : add to `packages/ccdi-models/src/metadata/field/description/harmonized/sample.rs`
 -  Missing from the wiki when running `cargo run -Znext-lockfile-bump --bin ccdi-spec --release wiki sample` . Not sure what file needs to be updated to fix this.

**Curated Uberon CSV**
I'm excited about this but I wasn't able to figure out how to run it on my checkout; I suspect no code changes needed here.

```rust
% cargo run --bin ccdi-curate -Znext-lockfile-bump

   Compiling ccdi-curate v1.0.0 (/Users/ekephart/repos/ccdi-federation-api/packages/ccdi-curate)
error[E0658]: use of unstable library feature 'lazy_cell'
 --> ccdi-curate/src/uberon.rs:4:5
  |
4 | use std::sync::LazyLock;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
  = help: add `#![feature(lazy_cell)]` to the crate attributes to enable

[three similar errors snipped...]

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ccdi-curate` (bin "ccdi-curate") due to 4 previous errors
```
I tried putting `#![feature(lazy_cell)]` in `ccdi-curate/src/uberon.rs` but that gave me further errors and I abandoned it at that point. I haven't updated Rust since my initial install; do you think that might be a next step?

**Comment by e-t-k** [comment]
@claymcleod
Yes, let's make this an array field with an OR relationship. That is to say, multiple values in the anatomical site array of a sample would indicate that the sample's anatomical site is ONE OF those values, but it is not known or not shared which value it is. 

That raises the question, though, is this EXACTLY ONE OF or AT LEAST ONE OF? I would argue for AT LEAST ONE OF, which would then cover the `[temporal lobe, frontal lobe]` use case that @GeoffLyle  mentioned at the Nov 8 meeting. However, this does add additional complexity for the users.

As discussed, this should not be used to list less-granular synonyms to the most precise known site; eg, it would be incorrect for the site to include `[cortex, brain]` 

Finally, let's decide how we want to handle filtering for samples with multiple sites.
- if a sample had anatomical sites  eg`[bone, lung]`, should it be retrieved from the query `sample?anatomical_site=bone`? I lean on yes; downstream users can then exclude these results if they want to be certain that their results are only the requested site.
- How should we construct a query to explicitly retrieve these samples (if indeed we should)? For example,  `sample?anatomical_site=lung,bone`, order-agnostic.

**Comment by claymcleod** [comment]
Yeah that all sounds correct to me. Regarding the filtering, I think we would keep the current stance on that for existing multi-value elements which is:

- For your first example, yes that would show up because the query exactly matches _one_ of the provided terms,
- There isn't support for "OR" within the query terms today—if you want to ask that kind of question, you'll have to do multiple queries (`/sample?anatomical_site=lung` and then `/sample?anatomical_site=bone`) and then merge the results yourself.

**Comment by GeoffLyle** [comment]
@claymcleod 
I agree with having an array with an OR relationship.  Given that this in the /sample endpoint, my use case was for diffuse samples brain tumors that span across multiple sites.  I believe it was also brought up that we could include multiple sites in the case of imprecise information (ex. we know it's from the `bran `or `lung` but not 100% sure which).  To account for both of these use cases I agree with the AT LEAST ONE OF definition for OR.

Best practices are for contributors to harmonize to the most accurate, specific, anatomic site, using a more general node if a specific site is not present in Uberon.  When an array of values is provided, it is used for samples that span across two precise locations or in the case of imprecise or missing information.

**Pull request merged**
